#!/usr/bin/env bash
# Script that configures 404 not found page

SU="sudo"
DIR_SERVER="/var/www/html/"
ERROR404="server {\n\terror_page 404 \/error404.html;"
DIR="/etc/nginx/sites-available/default"


if [ ! -x /usr/sbin/nginx ]; then
	sudo apt -y update
	sudo apt install -y --allow-downgrades nginx
	sudo ufw allow 'Nginx HTTP'
fi
$SU echo "Ceci n'est pas une page" > "${DIR_SERVER}error404.html"

sed -i "s/^server\s{/$ERROR404/1" $DIR
$SU service nginx restart

