#!/usr/bin/env bash
# Script that configures 404 not found page

if [ ! -x /usr/sbin/nginx ]; then
	sudo apt -y update
	sudo apt install -y --allow-downgrades nginx
	sudo ufw allow 'Nginx HTTP'
fi

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html;

str_to_add="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html{\n\t\troot /var/www/html;\n\t\tinternal;";

str_to_find="server_name _;";

sudo sed -i "/$str_to_find/a\\$str_to_add" /etc/nginx/sites-available/default;
sudo service nginx restart;

