#!/usr/bin/env bash
# Script that install and set up a Load balancer


# if [ ! -x /usr/sbin/haproxy  ]; then
sudo apt -y update
sudo apt-get -y install haproxy
sudo ufw allow 'haproxy'
# fi



echo "
listen server_request
        bind *:80
        mode http
        option httpchk
        server webserver1 35.229.20.253:80 check
        server webserver2 34.207.145.16:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg;


sudo service haproxy restart




