#!/usr/bin/env bash
# Scripts that fix the issue with nginx
sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default  /etc/nginx/sites-enabled/default
sudo service nginx restart

