#!/usr/bin/env bash
#Write a Bash script that displays:
#   To infinity and beyond indefinitely
#   With a sleep 2 in between each iteration
#   I am invincible!!! when receiving a SIGTERM signal

string="To infinity and beyond"

while : 
do
	echo "$string"
	sleep 2
	if []
done
