#!/usr/bin/env bash
# Script that run nginx as another user
chmod 644 /etc/nginx/nginx.conf
pkill -9 apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart

